### ISSUE TITLE
Syntax is out of date (compile error)

### ISSUE THREAD

**Issue by TPei** [veelenga/aasm.cr#5]
Hey, apparently the syntax is outdated in some places, making this shard unusable for me
- [x] type declaration with default values: order changed (https://github.com/veelenga/aasm.cr/pull/4)
- [x] type inference not possible everywhere (https://github.com/veelenga/aasm.cr/pull/6)

**Comment by veelenga** [comment]
Hey, you are right. At the moment it does not support latest crystal changes. I'm going to update it asap ;)
